/* AUTOGENERATED FILE - DO NOT MODIFY! */
#ifndef LR11XX_ALMANAC_H
#define LR11XX_ALMANAC_H

#include <zephyr.h>
#include <lr11xx_gnss_types.h>

extern lr11xx_gnss_almanac_full_read_bytestream_t lr11xx_full_almanac;

#endif